# Configuration for the DAM application using PostgreSQL

# --- Filesystem World ---
# This world will store its migrations in a custom local directory.
[worlds.fs_world]


[worlds.fs_world.plugin_settings.core]
database_url = "postgresql+psycopg://postgres:postgres@localhost:5432/dam"
alembic_path = "./dam_storage/fs_world_migrations"

[worlds.fs_world.plugin_settings."dam-fs"]
asset_storage_path = "./dam_storage/fs_world_asset_storage"

[worlds.fs_world.plugin_settings."dam-domarkx"]